### ISSUE TITLE
[OCIO] Handling of negatives values

### ISSUE THREAD

**Issue by MrLixm** [MrLixm/AgXc#11]
Following #9, I discovered that the ocio config is not handling negative properly in the `AgX Log` transform.

Initially I was using this kind of combinaison of transform to create a negative clamp :
```yaml
- !<AllocationTransform> { allocation: lg2, vars: [ -10, 7, 0.0056065625 ] }
- !<FileTransform> { src: dummy.spi1d, interpolation: linear }
- !<AllocationTransform> { allocation: lg2, vars: [ -10, 7, 0.0056065625 ], direction: inverse }
...
```
The dummy LUT clipping to 0-1 range, but this actually doesn't work and introduce more negatives because of the `<AllocationTransform>`.

As such this has been removed in #10 .

# Objective

Find a way to clamp negative values before the Matrix + Log2 transform are applied

# Comparison

![test_log after](https://user-images.githubusercontent.com/64362465/206873550-2c53c723-a779-464c-922b-8ac66df94c2e.jpg)
↳ img1 current behavior

![test_log ref](https://user-images.githubusercontent.com/64362465/206873553-8cac63dc-d333-40ba-b650-ea64a6b25091.jpg)
↳ img2 original AgX on OCIOv2

![test_log reference negatives](https://user-images.githubusercontent.com/64362465/206851103-9811ebc6-8ab6-486a-967d-cd7b9ce46f60.jpg) ↳ img3 reference image (unprocessed) - negatives mask

You can see some hard clipping on the small ColorsBars that initially have a lot of negatives.

**Comment by sobotka** [comment]
Given that the only recourse appears to be the dummy LUT, surely there is a mechanism to apply this pre-log?

I am still wondering why a simple clip post log, at the appropriate value range, is not working here, so perhaps you can elaborate?

At any rate, the allocation transform can also serve up a `uniform` distribution such that the desired range is normalized to the range specified. I would think that a reasonable range could work without introducing tremendous quantisation errors?

**Comment by MrLixm** [comment]
Hey Troy,

Here is why I am applying the clip post-log :
![image](https://user-images.githubusercontent.com/64362465/207173299-7f873a75-a4d6-4337-9470-39b079e1c382.png)
↳ white = negatives
corresponding transform :
```yaml
    from_reference: !<GroupTransform>
      children:
        - !<MatrixTransform> { matrix: [ 0.842479062253094, 0.0784335999999992, 0.0792237451477643, 0, 0.0423282422610123, 0.878468636469772, 0.0791661274605434, 0, 0.0423756549057051, 0.0784336, 0.879142973793104, 0, 0, 0, 0, 1 ] }
        - !<AllocationTransform> { allocation: lg2, vars: [ -12.47393, 4.026069] }
```

As you can see the lg2 transform introduced negative on all pure black values and leave the original negatives value that were not clip. 
So by clipping I' making sure that at least the initially pure black value, get back to `(0.0,0.0,0.0)`. Inital negatives are still fucked up but that is the reason of this ticket.

Also nice tip for the uniform transform, didn't even thought of it. I think using it in the pre-clip might actually fix my issue. Let me try.

**Comment by MrLixm** [comment]
Alright quick test of your proposition but no success.
Using :
```yaml
  - !<ColorSpace>
    name: AgX Log (Kraken)
    family: AgX
    equalitygroup: ""
    bitdepth: 32f
    description: AgX Log (Kraken)
    isdata: false
    allocation: uniform
    allocationvars: [ -12.47393, 4.026069 ]
    from_reference: !<GroupTransform>
      children:
        - !<AllocationTransform> { allocation: uniform, vars: [ -12.47393, 4.026069 ] }
        - !<FileTransform> { src: dummy.spi1d, interpolation: linear }
        - !<AllocationTransform> { allocation: uniform, vars: [ -12.47393, 4.026069 ], direction: inverse }
```
so with an uniform transform this time, no luck same issue and I don't know why.

The negatives are not clipped at all :

![image](https://user-images.githubusercontent.com/64362465/207176112-edc901bc-d647-412a-b00c-371ca47dc4e8.png)

AllocationTransform still looks like black magic to me and I don't understand what's going on, because if the LUT hack is working prost-log, why it isn't working pre-log ?
